default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  prepared_statements: false

development:
  primary:
    <<: *default

test:
  primary:
    <<: *default

production:
  primary:
    <<: *default

  cache:
    <<: *default

  queue:
    <<: *default

  cable:
    <<: *default
